Skip NetworkStatsBinderTest if the binder interface is not accessible.
Following up from aosp/3313055, the binder interface getUidStats(II)J
is removed from the module. Currently, the test catches
NoSuchMethodException for reflection.
But did not properly skip for NoSuchMethodError which is thrown by
the java runtime when a method was present during compilation is
no longer available.

Test: cts-tradefed run commandAndExit cts -m CtsNetTestCases -t \
     android.net.cts.NetworkStatsBinderTestinderTest
Bug: 378982661
Merged-In: I7b8baa7ab98ce0114541bf1a9568db6f832213b6
Change-Id: I7b8baa7ab98ce0114541bf1a9568db6f832213b6
(cherry picked from commit e4f2d94067138c34e66d65e272f311c5c921da9c [formerly 05b57b77243037c4ee06104c40e24691ceeb6202])

Former-commit-id: c43d56895fbb332f3f619b7e898c84d55a495d93