ConnectivityManagerTest#testOpenConnection: skip Cuttlefish
due to:

android.net.cts.ConnectivityManagerTest#testOpenConnection: FAILED (277ms)

STACKTRACE:
java.lang.AssertionError: Same address '104.135.180.196' on two different networks (153, 143)
  at org.junit.Assert.fail(Assert.java:89)
  at org.junit.Assert.assertTrue(Assert.java:42)
  at org.junit.Assert.assertFalse(Assert.java:65)
  at android.net.cts.ConnectivityManagerTest.testOpenConnection(ConnectivityManagerTest.java:934)

This would possibly be fixed by cuttlefish having IPv6 connectivity, but it doesn't atm.

@RequiresDevice doesn't work right with atest.

Test: TreeHugger
Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: I5bd4189ed6297a2491dc0ab7b251ffd19d1ecb5d

Former-commit-id: 5d9885da86133097dff114bab36df28e9bfd4543